// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdshsnymrybpysrvdlof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkc2hzbnltcnlicHlzcnZkbG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTczMTAsImV4cCI6MjA3MjA3MzMxMH0.dcT7Ozb-QREyevAwwQB9WqnzUAJzh2h7hV5Nrvmuul0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});